apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: template_user
    secureJsonData:
      password: template_secret
    jsonData:
      database: template_db
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    editable: true
